/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sptr.presentation;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import sptr.controleur.Simulateur;

/**
 *
 * @author HP
 */
public class InterfaceSPTR extends javax.swing.JFrame {

    private static Simulateur simulateur = new Simulateur();
    private static Afficheur afficheur;
    /**
     * Creates new form InterfaceSPTR
     */
//    public InterfaceSPTR() {
//        initComponents();
//    }
    
    
    public InterfaceSPTR(Simulateur s, Afficheur a)
    {
        initComponents();
        this.simulateur = s;
        this.simulateur = new Simulateur("sptr-scenario.xml");
        this.afficheur = a;
        initMapWithXMLFile();
        showParameter.setText(this.simulateur.getParametres().toString());
        
    }
    
    private void initEmptyMap()
    {
        for(int i = 0; i < 1024; i++)
        {
            JLabel tmpLabel = new JLabel();
            tmpLabel.setIcon(new javax.swing.ImageIcon("/home/bhacaz/Dropbox/Ulaval/H-16/SPTR/SPTR/src/main/java/sptr/res/empty.png")); // NOI18N
            imageGrid.add(tmpLabel);
        }
    }
    
    private void initMapWithXMLFile()
    {
        for(ArrayList<String> als : this.simulateur.getImageMap())
        {
            for(String imageName : als)
            {
                JLabel tmpLabel = new JLabel();
                tmpLabel.setPreferredSize(new java.awt.Dimension(64, 64));
                tmpLabel.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/" + imageName))); // NOI18N
                imageGrid.add(tmpLabel);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResultat = new javax.swing.JLabel();
        demarerSimulationButton = new javax.swing.JButton();
        chooseXMLFileButton = new javax.swing.JButton();
        imageGrid = new javax.swing.JPanel();
        carteRoutiereLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showParameter = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuFichier = new javax.swing.JMenuItem();
        jMenuParametres = new javax.swing.JMenuItem();
        jMenuQuitter = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelResultat.setText("Resultats");
        getContentPane().add(jLabelResultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        demarerSimulationButton.setText("Demarer simulation");
        demarerSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demarerSimulationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(demarerSimulationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 170, -1));

        chooseXMLFileButton.setText("Fichier XML");
        chooseXMLFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseXMLFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chooseXMLFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, -1));

        imageGrid.setPreferredSize(new java.awt.Dimension(200, 200));
        imageGrid.setLayout(new java.awt.GridLayout(32, 32));
        getContentPane().add(imageGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 830, 780));

        carteRoutiereLabel.setText("Carte routiere");
        getContentPane().add(carteRoutiereLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        showParameter.setText("jLabel1");
        showParameter.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(showParameter);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 230, 290));

        jMenu1.setText("File");

        jMenuFichier.setText("Ouvrir Fichier");
        jMenuFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFichierActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFichier);

        jMenuParametres.setText("Parametres");
        jMenuParametres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuParametresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuParametres);

        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuQuitter);

        Menu.add(jMenu1);

        jMenu4.setText("?");
        Menu.add(jMenu4);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFichierActionPerformed
        // TODO add your handling code here:
               String filePath = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
        
        simulateur.setFilePath(filePath);
        simulateur.readXML();
    }//GEN-LAST:event_jMenuFichierActionPerformed

    private void jMenuParametresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuParametresActionPerformed
        JFrame o = new ParametresWindows(simulateur.getParametres());
//        jDesktopPane1.add(o);
        o.setVisible(true);
    }//GEN-LAST:event_jMenuParametresActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Apropos a = new Apropos();
//        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void chooseXMLFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseXMLFileButtonActionPerformed
        // TODO add your handling code here:
               String filePath = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
        
        simulateur.setFilePath(filePath);
        simulateur.readXML();
        initMapWithXMLFile();
    }//GEN-LAST:event_chooseXMLFileButtonActionPerformed

    private void demarerSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demarerSimulationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demarerSimulationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceSPTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceSPTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceSPTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceSPTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceSPTR(simulateur, afficheur).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel carteRoutiereLabel;
    private javax.swing.JButton chooseXMLFileButton;
    private javax.swing.JButton demarerSimulationButton;
    private javax.swing.JPanel imageGrid;
    private javax.swing.JLabel jLabelResultat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuFichier;
    private javax.swing.JMenuItem jMenuParametres;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel showParameter;
    // End of variables declaration//GEN-END:variables
}

